### ISSUE TITLE
ECONNRESET crash on browser disconnection

### ISSUE THREAD

**Issue by andreyvit** [livereload/LiveReload#12]
UV-3239:

> Just got a crash using Windows version 0.8.4.0 
I was using Livereload with Safari for Windows 5.1.7 (Livereload extension 
2.0.9). The crash happened just at the moment I closed the browser.

The log:

    INCOMING: ["rpc",{"#mainwnd":{"#textBlockStatus":{"text":"Idle. 1 browser connected. 1 change, 0 files compiled, 1 refresh so far."}}}]
    STDERR: Thu, 21 Mar 2013 16:20:18 GMT wsio:drafts websocket-hixie received data packet {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://127.0.0.1:90/gcba/PortalFestivales-2013/htdocs/web/"}
    STDERR: Thu, 21 Mar 2013 16:20:18 GMT livereload:server LRWebSocketConnection(C3) received {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://127.0.0.1:90/gcba/PortalFestivales-2013/htdocs/web/"}
    STDERR: Thu, 21 Mar 2013 16:20:18 GMT livereload:core:session Ignoring unknown command info: {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://127.0.0.1:90/gcba/PortalFestivales-2013/htdocs/web/"}
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive Change: Stats0.connectionCount is now 0
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive Executing block MainWindow0_B0_render_status
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive MainWindow0_B0_render_status depends on MainWindow(#mainwnd).status
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive MainWindow0_B0_render_status depends on Stats0.connectionCount
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive MainWindow0_B0_render_status depends on Stats0.changes
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive MainWindow0_B0_render_status depends on Stats0.compilations
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT reactive MainWindow0_B0_render_status depends on Stats0.refreshes
    STDERR: Thu, 21 Mar 2013 16:20:20 GMT livereload:rpc Node to App: ["rpc",{"#mainwnd":{"#textBlockStatus":{"text":"Idle. 0 browsers connected. 1 change, 0 files compiled, 1 refresh so far."}}}]
    INCOMING: ["rpc",{"#mainwnd":{"#textBlockStatus":{"text":"Idle. 0 browsers connected. 1 change, 0 files compiled, 1 refresh so far."}}}]
    STDERR: 
    STDERR: events.js:72
    STDERR:         throw er; // Unhandled 'error' event
    STDERR:               ^
    STDERR: Error: read ECONNRESET
    STDERR:     at errnoException (net.js:863:11)
    STDERR:     at TCP.onread (net.js:524:19)
    Node.js appears to have crashed.
    LiveReload says bye.

**Comment by cam5** [comment]
FWIW, I get this error only when I have two instances of livereload.
